global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway-server:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'user-server'
    static_configs:
      - targets: ['user-server:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'map-server'
    static_configs:
      - targets: ['map-server:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'board-server'
    static_configs:
      - targets: ['board-server:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'photo-server'
    static_configs:
      - targets: ['photo-server:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-server'
    static_configs:
      - targets: ['notification-server:8085']
    metrics_path: '/actuator/prometheus'
